pub mod global_properties;
pub mod incidence_report;
pub mod infection_manager;
pub mod infection_seeder;
pub mod person_properties;
pub mod population_loader;
pub mod transmission_manager;
pub mod death_manager;
pub mod death_report;
